### ISSUE TITLE
generate_beta_pc_boxplot_long not plotting all paired lines 

### ISSUE THREAD

**Issue by kennyyeo13** [cafferychen777/MicrobiomeStat#13]
Hi Chen,

This is my plot, I have paired data inputted. But it seems to not plot paired lines for all. I have tried it with peerj32.obj and it worked fine. Wondering if you can help? 

Thanks 
Kenny

generate_beta_pc_boxplot_long(
+   data.obj = object,
+   dist.obj = NULL,
+   pc.obj = NULL,
+   subject.var = "ID",
+   time.var = "Tech",
+   group.var = "Sample_type",
+   t0.level = "1",
+   ts.levels = "2",
+   strata.var = NULL,
+   dist.name = c('BC'),
+   base.size = 20,
+   theme.choice = "bw",
+   custom.theme = NULL,
+   palette = NULL,
+   pdf = FALSE,
+   file.ann = NULL,
+   pdf.wid = 11,
+   pdf.hei = 8.5
+ )
Using table 'meta.dat' in 'data.obj'.
Using table 'feature.tab' in 'data.obj'.
Using table 'feature.ann' in 'data.obj'.
Using table 'meta.dat' in 'data.obj'.
Initializing distance objects...
Calculating Bray-Curtis dissimilarity...
All calculations complete.
No pc.obj provided, using MDS (PCoA) for dimension reduction by default.
If you prefer other methods such as NMDS, t-SNE or UMAP, you can use the mStat_calculate_PC function with a specified method.
Calculating PC...
Processing BC distance...
Calculating MDS...
Calculation complete.

![Rplot](https://github.com/cafferychen777/MicrobiomeStat/assets/89982724/4b74d6b9-0b6f-42a3-a848-b76ac7b35259)

**Comment by cafferychen777** [comment]
Hi Kenny,

Thank you for reaching out. From what you've described, it sounds like the issue arises due to the design of the `generate_beta_pc_boxplot_long` function in the MicrobiomeStat package. Specifically, when there's a concern about the plot becoming cluttered due to many subjects, we've set a threshold to limit the number of paired lines. If the number of subjects exceeds this threshold, only an average connecting line will be plotted instead of individual subject lines.

To address your specific issue, you can modify the code of the `generate_beta_pc_boxplot_long` function. Look for the line:

```R
if (n_times > 10 || n_subjects > 25) {
```

You can adjust the threshold value of `n_subjects` to a number that suits your dataset. For instance, if you wish to see paired lines for up to 50 subjects, you can change it to:

```R
if (n_times > 10 || n_subjects > 50) {
```

After making this change, you should be able to see paired lines for each subject up to the new limit you've set.

I hope this helps! Please let me know if you have any other questions or if there's anything else I can assist you with.

Best regards,
Chen

**Comment by kennyyeo13** [comment]
Thanks for the help!
