### ISSUE TITLE
Impossible to find the function "GUniFrac"

### ISSUE THREAD

**Issue by ladrub** [cafferychen777/MicrobiomeStat#28]
**Describe the Bug**
When I use the function `generate_beta_change_test_long` to calculate BC, Jaccard, UniFrac distances, I get the error "Impossible to find the function "GUniFrac""

**Screenshots**

![error_unifrac](https://github.com/cafferychen777/MicrobiomeStat/assets/100934857/b4a6da94-0215-45e3-801e-0d6e31eca2df)

**Environment Information:**

 - R Version: 4.3.1
 - Package Version: 1.1.3

**Attempted Solutions**
I updated MicrobiomeStats, the error also triggers when using other functions like `generate_beta_trend_test_long` or `generate_beta_volatility_test_long`.
The `data.obj` contains a tree object (rooted), I managed to compute Unifrac distances with the ordinate function from phyloseq package.

**Comment by cafferychen777** [comment]
Dear ladrub,

Thank you for reaching out and providing detailed information about the issue you're encountering with the "GUniFrac" function in the MicrobiomeStat package.

The error you're experiencing is likely due to the absence of the GUniFrac package in your R environment. Although GUniFrac is a crucial package for computing UniFrac distances, it is not automatically installed with MicrobiomeStat due to CRAN's restrictions on the number of dependencies a package can have.

To resolve this issue, please ensure that you explicitly load the GUniFrac package in your R session. You can do this by following these steps after setting `dist.name = "Unifrac"`:

1. Install the GUniFrac package (if you haven't already) by running:
```R
if (!requireNamespace("GUniFrac", quietly = TRUE)) {
    install.packages("GUniFrac")
}
```

2. Load the GUniFrac package using:
```R
library(GUniFrac)
```

After loading the GUniFrac package, the functions `generate_beta_change_test_long`, `generate_beta_trend_test_long`, and `generate_beta_volatility_test_long` should work as expected, utilizing the UniFrac distance computations.

Please let me know if this solution resolves the issue or if you have any further questions or concerns.

Best regards,

Chen YANG

**Comment by ladrub** [comment]
Dead cafferychen777,

Thank you a lot for your answer! It is working.

Have a good rest of the day.
