### ISSUE TITLE
Volcano overlapping labels_MicrobiomeStat_v1.1.3

### ISSUE THREAD

**Issue by 16svale** [cafferychen777/MicrobiomeStat#31]
### Discussed in https://github.com/cafferychen777/MicrobiomeStat/discussions/21

<div type='discussions-op-text'>

<sup>Originally posted by **cafferychen777** December  6, 2023</sup>
[MicrobiomeStat_1.1.3.tar.gz](https://github.com/cafferychen777/MicrobiomeStat/files/13578964/MicrobiomeStat_1.1.3.tar.gz)

<hr /><em>This discussion was created from the release <a href='https://github.com/cafferychen777/MicrobiomeStat/releases/tag/MicrobiomeStat_Version_1.1.3'>MicrobiomeStat_v1.1.3</a>.</em></div>

**Comment by cafferychen777** [comment]
Hi @16svale,

Thank you for reporting the volcano plot label overlapping issue!

## Issue Resolution ✅

This issue was **resolved** on **February 17, 2024** (one day after you reported it) in commit [6f3133b](https://github.com/cafferychen777/MicrobiomeStat/commit/6f3133b451474504f8dfc18b41e2cd62f63cf1ef).

### What Was Fixed

The overlapping labels issue was caused by using `geom_text()` which doesn't handle label positioning automatically. The fix involved:

**Before (v1.1.3)**:
```r
geom_text(
  aes(label = ifelse(get(p_val_var) < feature.sig.level, as.character(Variable), '')),
  vjust = -0.5,
  hjust = 0.5,
  size = 3.5
)
```

**After (v1.1.4+)**:
```r
ggrepel::geom_text_repel(
  aes(label = ifelse(get(p_val_var) < feature.sig.level, as.character(Variable), '')),
  size = 3.5,
  box.padding = 0.35,
  point.padding = 0.5,
  show.legend = FALSE
)
```

### Key Improvements

The `ggrepel::geom_text_repel()` function provides:
- **Automatic label positioning** to avoid overlaps
- **Connector lines** from labels to points (when needed)
- **Box padding** to create spacing around labels
- **Point padding** to keep labels away from data points

### Current Status

This fix is included in:
- ✅ All versions **≥ 1.1.4**
- ✅ Current latest version on GitHub

### How to Update

If you're still experiencing this issue, please update to the latest version:

```r
# Install latest version from GitHub
remotes::install_github("cafferychen777/MicrobiomeStat")
```

The overlapping labels issue should be completely resolved. If you're using the latest version and still seeing overlaps in specific cases, please let me know and I can investigate further!

Best regards,  
Chen Yang
