### ISSUE TITLE
Reference level for categorical variables

### ISSUE THREAD

**Issue by pbaCamille** [cafferychen777/MicrobiomeStat#68]
Hello,

I'm facing an issue with interpreting the results using the function ```generate_taxa_test_single```. 
I have a categorical variable and when I change the level order of the variables to switch the reference group, it changes the resultating dataframe name but it does not change the resulting Coefficient values. I expected that the log2FoldChange to change sign.

Maybe I'm missing something here, and I do not know how to interpret correctly my results.

Thank you in advance for your answer.

**Comment by cafferychen777** [comment]
Hello @Camille,

I've investigated your concern about the reference level switching in `generate_taxa_test_single`, and I can confirm that the function is working correctly. I've created a test case to verify this behavior:

```r
test_that("linda reference level switching works correctly", {
  # Create sample data
  set.seed(123)
  n_samples <- 40
  n_features <- 10
  
  # Create feature table
  feature.tab <- matrix(rpois(n_samples * n_features, lambda = 10), 
                       nrow = n_features, 
                       ncol = n_samples)
  rownames(feature.tab) <- paste0("Feature", 1:n_features)
  colnames(feature.tab) <- paste0("Sample", 1:n_samples)
  
  # Create metadata
  meta.dat <- data.frame(
    group = factor(rep(c("A", "B"), each = n_samples/2)),
    sex = factor(rep(c("M", "F"), times = n_samples/2))
  )
  rownames(meta.dat) <- colnames(feature.tab)
  
  # Create feature annotations
  feature.ann <- matrix(
    c(paste0("Phylum", rep(1:2, each = 5)),
      paste0("Genus", 1:n_features)),
    nrow = n_features,
    ncol = 2,
    dimnames = list(rownames(feature.tab), c("Phylum", "Genus"))
  )
  
  data.obj <- list(
    feature.tab = feature.tab,
    meta.dat = meta.dat,
    feature.ann = feature.ann
  )
```

The test results show that when switching reference levels:

1. The coefficients do change sign correctly
2. P-values remain the same
3. Standard errors remain unchanged

Here's a comparison of results when switching reference levels:

```
=== Test 1 Results (A as reference) ===
Result names: B vs A (Reference) 

First few rows:
  Variable  Coefficient        SE   P.Value
1   Genus1  0.026154835 0.1489754 0.8615932
2  Genus10 -0.005405507 0.1487778 0.9712124
3   Genus2 -0.064312337 0.1192832 0.5930083

=== Test 2 Results (B as reference) ===
Result names: A vs B (Reference) 

First few rows:
  Variable  Coefficient        SE   P.Value
1   Genus1 -0.026154835 0.1489754 0.8615932
2  Genus10  0.005405507 0.1487778 0.9712124
3   Genus2  0.064312337 0.1192832 0.5930083
```

As you can see:
- When switching from A to B as reference, the coefficients change sign (e.g., 0.026154835 → -0.026154835)
- P-values and standard errors remain identical
- The dataframe names correctly reflect the reference level change

This is the expected behavior in linear modeling - changing the reference level should:
1. Reverse the sign of the coefficients (because we're measuring the opposite contrast)
2. Maintain the same statistical significance
3. Keep the same standard errors

Let me know if you need any clarification or have additional questions!

**Comment by cafferychen777** [comment]
P.S. To correctly change the reference level of your categorical variable, you can use one of these R methods:

1. Using `relevel()` (recommended):
```r
# If your data is in data.obj
data.obj$meta.dat$your_group_var <- relevel(data.obj$meta.dat$your_group_var, ref = "desired_reference_level")

# Or if you have a regular dataframe
your_data$group <- relevel(your_data$group, ref = "desired_reference_level")
```

2. Using factor() with levels specified:
```r
# Explicitly specify the order of levels, putting your reference level first
data.obj$meta.dat$your_group_var <- factor(data.obj$meta.dat$your_group_var, 
                                          levels = c("desired_reference_level", "other_level"))
```

3. To check the current reference level:
```r
# View current levels (first one is the reference)
levels(data.obj$meta.dat$your_group_var)
```

Make sure to change the reference level before running `generate_taxa_test_single()`. The first level in your factor will be used as the reference group.

**Comment by pbaCamille** [comment]
Thank you for your quick answer, 
Indeed, I was expecting this behavior : Reverse the sign of the coefficients by switching the reference order.

My bad, I wasn't using the recommended function ```relevel``` and it seems that alphabetic order was used.
